In [1]:
import numpy as np
import pandas as pd

In [4]:
file_path = "Landing Zone Dataset - Sheet1.csv"
df = pd.read_csv(file_path)

In [8]:
df.head(10)

,slope_deg,roughness,edge_density,ndvi_mean,shadow_fraction,brightness_std,object_density,confidence_score,label
0,10.483571,0.066756,0.099523,0.398224,0.297286,0.067727,0.182327,0.741485,1
1,7.308678,0.105711,0.377215,0.669015,0.057829,0.147740,0.272118,0.837913,1
2,11.238443,0.535800,0.067437,0.438767,0.198451,0.132821,0.140229,0.802620,0
3,15.615149,0.159571,0.182308,0.081362,0.379600,0.124568,0.170602,0.777006,1
4,6.829233,0.122880,0.129803,0.492456,0.110414,0.156328,0.044424,0.885057,1
5,6.829315,0.309956,0.400471,0.797920,0.257420,0.139357,0.168228,0.838910,0
6,15.896064,0.500674,0.243578,0.027790,0.035379,0.206065,0.108030,0.887366,0
7,11.837174,0.192533,0.373597,0.673435,0.333952,0.104338,0.069596,0.926176,1
8,5.652628,0.679814,0.145377,0.188385,0.113591,0.111459,0.088224,0.849190,0
9,10.712800,0.165807,0.215131,0.315093,0.134647,0.188578,0.225000,0.738388,1

In [23]:
df.tail(10)

,slope_deg,roughness,edge_density,ndvi_mean,shadow_fraction,brightness_std,object_density,confidence_score,label
2990,15.581970,0.125753,0.487732,0.364493,0.201990,0.090180,0.212443,0.754982,0
2991,11.010592,0.306492,0.323253,0.183404,0.084186,0.111774,0.203779,0.653420,0
2992,8.360184,0.364157,0.225326,0.576972,0.130314,0.159507,0.205360,0.616755,1
2993,6.938955,0.216440,0.224236,0.776190,0.368520,0.152174,0.219515,0.910191,1
2994,3.240408,0.473130,0.139592,0.652288,0.131787,0.112278,0.091936,0.756332,1
2995,8.387403,0.280633,0.187511,0.028223,0.028989,0.158808,0.092506,0.862487,1
2996,9.288763,0.280493,0.363842,0.253328,0.098522,0.207909,0.061030,0.773716,0
2997,1.791197,0.383695,0.474818,0.022864,0.300682,0.152782,0.502573,0.907883,0
2998,9.670882,0.338289,0.202693,0.032134,0.284579,0.087041,0.016859,0.862383,0
2999,7.223705,0.283629,0.456172,0.063612,0.275099,0.144804,0.374206,0.629910,0

In [22]:
df.shape

(3000, 9)

In [26]:
np.sum(df.isna(), axis = 0)

slope_deg           0
roughness           0
edge_density        0
ndvi_mean           0
shadow_fraction     0
brightness_std      0
object_density      0
confidence_score    0
label               0
dtype: int64

### No missing values

In [14]:
print(np.mean(df["label"]))

0.55

### Data has more 1 label points than 0 label points

In [31]:
print("\n\n----------------------------------------------x----------------------------------------------\n\n")

----------------------------------------------x----------------------------------------------

#### slope of the surface to land. 0 slope means flat ground. more slope means tilted
#### roughness gives the texture of the surface. 0 means even/ smooth. more means jagged and rough
#### edge_density is how many sharp edges in image. more means cuts or different surfaces 
#### ndvi is to measure healthy plants. more in the image means more area covered by vegetation
#### shadows in the image. if more of image has shadow, its values may be unreliable. cant detect color or edges properly
#### brightness standard deviation. if it is low, uniform floor. if high, then floor is made of different materials 
#### object density. if more objects present in image, more uncertainity about landing surface 
#### confidence in detecting the features from image. if more condifence score, then more reliable the numbers. 
### From our perspective, we want all features to be as low as possible except the confidence score. High confidence score is better

In [32]:
print("\n\n----------------------------------------------x----------------------------------------------\n\n")

----------------------------------------------x----------------------------------------------

In [30]:
df.describe()

,slope_deg,roughness,edge_density,ndvi_mean,shadow_fraction,brightness_std,object_density,confidence_score,label
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,8.257786,0.287347,0.335261,0.397403,0.245188,0.151231,0.219207,0.775345,0.550000
std,4.729597,0.157635,0.176202,0.229965,0.142418,0.050393,0.130930,0.100204,0.497577
min,0.000000,0.005368,0.000868,0.000004,0.005999,-0.018778,0.004051,0.600259,0.000000
25%,4.862294,0.167848,0.198709,0.196411,0.134075,0.117025,0.120339,0.689372,0.000000
50%,8.121824,0.266516,0.319744,0.398755,0.224382,0.151421,0.196254,0.776927,1.000000
75%,11.367954,0.390529,0.451383,0.589366,0.337315,0.186058,0.298400,0.863509,1.000000
max,27.631189,0.819733,0.901881,0.799831,0.756748,0.314608,0.765969,0.949867,1.000000

## Check for outliers

### From min, max values we can there is negative values for brightness_std
### If it is standard deviation of brightness values, there can't be a negative value possible

In [66]:
df[df["brightness_std"] < 0]

,slope_deg,roughness,edge_density,ndvi_mean,shadow_fraction,brightness_std,object_density,confidence_score,label
34,12.112725,0.472738,0.330814,0.236846,0.265162,-0.003378,0.252713,0.643553,0
391,10.459596,0.309331,0.299155,0.142162,0.217129,-0.009845,0.298352,0.673360,1
2091,9.502372,0.259331,0.313779,0.103443,0.200045,-0.006781,0.103990,0.779281,0
2174,3.824285,0.239882,0.236380,0.502552,0.093061,-0.018778,0.278978,0.604358,1
2191,10.310863,0.363551,0.584860,0.024559,0.293025,-0.017120,0.478612,0.730381,0

### These are wrong values. They need to be dropped

## Next check based on IQR fencing

In [33]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
lower_fence = Q1 - IQR
upper_fence = Q3 + IQR

outliers_mask1 = df < lower_fence
outliers_mask2 = df > upper_fence

In [41]:
print(outliers_mask1.sum(axis = 0))
print("\n\n----------------------------------------------x----------------------------------------------\n\n")
print(outliers_mask1.sum(axis = 1).sum())

slope_deg            0
roughness            0
edge_density         0
ndvi_mean            0
shadow_fraction      0
brightness_std      56
object_density       0
confidence_score     0
label                0
dtype: int64


----------------------------------------------x----------------------------------------------


56

In [44]:
print(outliers_mask2.sum(axis = 0))
print("\n\n----------------------------------------------x----------------------------------------------\n\n")
print(outliers_mask2.sum(axis = 1))

slope_deg            78
roughness            96
edge_density         81
ndvi_mean             0
shadow_fraction     107
brightness_std       41
object_density      138
confidence_score      0
label                 0
dtype: int64


----------------------------------------------x----------------------------------------------


0       0
1       0
2       0
3       0
4       0
       ..
2995    0
2996    0
2997    1
2998    0
2999    0
Length: 3000, dtype: int64

In [50]:
df_temp = outliers_mask2.sum(axis = 1)
df_temp.max()

3

In [64]:
print(df_temp[df_temp > 0].shape)
print(df_temp[df_temp > 1].shape)
print(df_temp[df_temp > 2].shape)
print(df_temp[df_temp == 1].shape)
print(df_temp[df_temp == 2].shape)
print(df_temp[df_temp == 3].shape)

(496,)
(44,)
(1,)
(452,)
(43,)
(1,)

In [63]:
df_temp[(df_temp > 0) & (df["confidence_score"] < 0.7)].shape

(135,)

#### can use a threshold if the value is outlier based on IQR
#### thres 1 will drop 496 + 56 rows. thres 2 will drop 44. and thres 3 will drop 1 row. 
#### can also use a combined method where the value falls as outlier based on IQR and its confidence score is low
#### this method may be good if there are rows with low confidence score such as < 0.5 
#### our data has lowest confidence score of 0.6 so this method may not be preferred
#
## These are ignored for this project. But cleaning based on this criteria may be useful if we have large dataset

In [74]:
print("\n\n----------------------------------------------x----------------------------------------------\n\n")

----------------------------------------------x----------------------------------------------

## Feature analysis
### Check if any feature has odd behaviour
### Skewness to check how close it is to normal distribution
### Correlation to check if features are independent
### Otherwise we may need to use PCA to get reliable features to train model on

In [73]:
df.skew()

slope_deg           0.273657
roughness           0.566269
edge_density        0.424703
ndvi_mean           0.011745
shadow_fraction     0.708842
brightness_std     -0.073671
object_density      0.836820
confidence_score   -0.036305
label              -0.201108
dtype: float64

### We can see a bit of skewness in shadow_fraction and object_density
### This means there are more data points towards the minimum 
### As less shadows and objects are preferred, there are more data points that have that
### It is not a problem unless our real world environment is expected to have a lot of shadows and objects

In [75]:
df.corr()

,slope_deg,roughness,edge_density,ndvi_mean,shadow_fraction,brightness_std,object_density,confidence_score,label
slope_deg,1.000000,0.007190,0.007604,-0.005290,0.007518,-0.012251,-0.031650,0.029672,-0.312293
roughness,0.007190,1.000000,-0.002291,0.027424,-0.010306,0.036299,0.032336,-0.012592,-0.237614
edge_density,0.007604,-0.002291,1.000000,-0.012560,0.010261,-0.006144,0.041667,0.014201,-0.194533
ndvi_mean,-0.005290,0.027424,-0.012560,1.000000,-0.047762,-0.001751,-0.018842,-0.028508,0.179387
shadow_fraction,0.007518,-0.010306,0.010261,-0.047762,1.000000,0.010010,0.012170,-0.000970,-0.128995
brightness_std,-0.012251,0.036299,-0.006144,-0.001751,0.010010,1.000000,0.011337,0.017071,-0.014380
object_density,-0.031650,0.032336,0.041667,-0.018842,0.012170,0.011337,1.000000,-0.005310,-0.105365
confidence_score,0.029672,-0.012592,0.014201,-0.028508,-0.000970,0.017071,-0.005310,1.000000,-0.000069
label,-0.312293,-0.237614,-0.194533,0.179387,-0.128995,-0.014380,-0.105365,-0.000069,1.000000

### Theres no strong correlation between features
### As expected, most of the features are inversely correlated to the label
### But surprisingly NDVI has a positive correlation with outcome. Maybe the value represents something other than what we expected